/** Common throwaway / temp-mail domains — extend as needed. */
const DISPOSABLE_DOMAINS = new Set([
  'mailinator.com',
  'guerrillamail.com',
  'guerrillamail.net',
  'guerrillamail.org',
  'sharklasers.com',
  'grr.la',
  'tempmail.com',
  'temp-mail.org',
  'temp-mail.io',
  '10minutemail.com',
  '10minutemail.net',
  'yopmail.com',
  'yopmail.fr',
  'trashmail.com',
  'trashmail.me',
  'getnada.com',
  'dispostable.com',
  'maildrop.cc',
  'fakeinbox.com',
  'mintemail.com',
  'emailondeck.com',
  'throwaway.email',
  'mailnesia.com',
  'spamgourmet.com',
  'mytemp.email',
  'tempail.com',
  'moakt.com',
  'inboxkitten.com',
  'mailcatch.com',
  'getairmail.com',
  'mail.tm',
  'tempinbox.com',
  'burnermail.io',
  'mailsac.com',
  'dropmail.me',
  'harakirimail.com',
  'mailpoof.com',
  'fakemail.net',
  'crazymailing.com',
  'tempr.email',
  'emailfake.com',
  'generator.email',
  'mailforspam.com',
  'spambox.us',
  'mailnull.com',
  'spam4.me',
  'discard.email',
  'tmpmail.net',
  'tmpmail.org',
  'mail-temp.com',
  'tempmailo.com',
  'emailnax.com',
  'inboxbear.com',
  'spamdecoy.net',
  'mailscrap.com',
]);

export function isDisposableEmailDomain(email: string): boolean {
  const at = email.trim().toLowerCase().lastIndexOf('@');
  if (at <= 0) return false;
  const domain = email.slice(at + 1).trim().toLowerCase();
  return DISPOSABLE_DOMAINS.has(domain);
}
